### ISSUE TITLE
How to write received data in String?

### ISSUE THREAD

**Issue by LeMoussel** [alexcrichton/curl-rust#117]
How can I write received data in String?
I do this 
```
let html: String = String::new();
easy.write_function(|data| {
        let html = String::from_utf8(Vec::from(data)).unwrap();
        Ok(data.len())
}).unwrap();
println!("{}", html);
```
But there is nothing in `html` string variable.  I think `let html = String::from_utf8 ...` is local and not the same as `let html: String ...`

**Comment by LeMoussel** [comment]
Solution with the use of [transfer](http://alexcrichton.com/curl-rust/curl/easy/struct.Easy.html#method.transfer) method.

```
    let mut html: String = String::new();
    {
        let mut transfer = easy.transfer();
        transfer.write_function(|data| {
            html = String::from_utf8(Vec::from(data)).unwrap();        
            // html.push_str(str::from_utf8(data).unwrap());          
            Ok(data.len())
        }).unwrap(); 

        transfer.perform().unwrap();
    }
```
I'm newbie with Rust. What is right method?
`html = String::from_utf8(Vec::from(data)).unwrap();`
or
`html.push_str(str::from_utf8(data).unwrap());`

**Comment by alexcrichton** [comment]
Indeed! I believe you want `transfer` here which allows further closures stack access to variables (so you can actually collect the response). The `Easy::write_function` method is useful for firing off the data elsewhere (aka the console), but if you need access to it the `'static` bound on the closure can get cumbersome.

Here you'll actually want to use `push_str` because the `write_function` can be called multiple times (with different chunks of data). You may also want to collect into a `Vec` and then perform the UTF-8 validation all at once (may be a bit speedier), but `push_str` should work regardless.

You might be interested in the [second example](https://github.com/alexcrichton/curl-rust#quick-start) in the README as that also shows collecting data into a local vector.

**Comment by alexcrichton** [comment]
Closing, but feel free of course to ask any more questions!
