### ISSUE TITLE
Segmentation fault on incorrect use of Transfer

### ISSUE THREAD

**Issue by ishbir** [alexcrichton/curl-rust#122]
So I'm a new to Rust in general and was playing around with `curl-rust` when I got a segfault on calling the following function:
```rust
fn get_page(session: Box<IoFuture<Session>>) -> Box<Future<Item = String, Error = std::io::Error>> {

    session.and_then(|sess| {
        // Prepare the HTTP request to be sent.
        let mut req = Easy::new();
        req.get(true).unwrap();
        req.url("https://www.rust-lang.org").unwrap();
        
        req.transfer()
            .write_function(|data| {
                Ok(data.len())
            })
            .unwrap();

        sess.perform(req).map(|_e| "blah".to_owned())
    })
        .boxed()
}
```
I'm pretty sure it results from an incorrect usage of Transfer but the code shouldn't even compile.. memory safety is being violated somewhere.

Further investigation using gdb revealed that the culprit is:
```
Thread 1 "demo" received signal SIGSEGV, Segmentation fault.
0x00005555555e7ea2 in curl::easy::transfer_write_cb::{{closure}}::{{closure}} (
    f=0x7ffff4ac7000)
    at /home/random/.cargo/registry/src/github.com-1ecc6299db9ec823/curl-0.3.3/src/easy.rs:2761
2761	        (*(data as *mut TransferData)).write.as_mut().map(|f| f(buf))
```

Oh and it would be great if someone could suggest me a way to accomplish what I want (return the webpage retrieved as a Future that returns String) using the futures crate.

**Comment by alexcrichton** [comment]
Oh dear, this is indeed quite bad! I'll look into a fix. 

FWIW though maybe [this test](https://github.com/alexcrichton/futures-rs/blob/master/futures-curl/tests/smoke.rs#L16) could help in how to download?

**Comment by alexcrichton** [comment]
Ok, I've pushed a commit which I believe addresses the segfault, although unfortunately not be preventing the example to compile but rather just fixing it up at runtime.

The underlying problem here is that configuration on a `.transfer()` is only active and valid for that transfer itself. Once the `Transfer` object is dropped then all of its configuration goes away as well (morally at least).

To collect data you'll need to register a `.write_function()` on the `Easy` handle itself rather than the `Transfer`. Does that make sense?
