### ISSUE TITLE
closure argument to `Easy::write_function()` should not need `Send` bound

### ISSUE THREAD

**Issue by dwrensha** [alexcrichton/curl-rust#139]
(As mentioned here: https://github.com/tokio-rs/tokio-curl/issues/3#issuecomment-247162572)

Is there any particular reason for this bound? My understanding is that all of the work happens on the same thread.

**Comment by alexcrichton** [comment]
Yeah this is something I've been meaning to fix for awhile as it's too restrictive when using tokio-curl most of the time. The reason here is that the closures are all generics, but I don't want the `Easy` handle type to have a bazillion type parameters. When erasing through trait objects though I decided to have `Easy` itself be sendable, which forced closures to be `Send`.

My preference for how to fix this is something like:


```rust
struct Easy2<C> {
    // ...
}

impl<C: EasyCallbacks> Easy2<C> {
    pub fn new(callbacks: C) -> Easy2<C> {
        // ...
    }

    // copy the rest of the `Easy` API here, minus callback functions
}

trait EasyCallbacks {
    // Rust signature for each curl callback 
}
```

That way through the use of generics this should still be quite ergonomic to use and we can plumb through whether it's `Send`/`'static` all the way to the end. I think the current `Easy` type can then be built on top of the `Easy2` type as it'd just have an implementation of `EasyCallbacks` that stores a bunch of trait objects.

I haven't gotten around to implementing this just yet, unfortunately though.
