### ISSUE TITLE
Expose `curl_easy_setopt` and `curl_easy_getinfo` as unsafe functions.

### ISSUE THREAD

**Issue by ebarnard** [alexcrichton/curl-rust#326]
It would be useful to have these functions exposed so users can change less common options without needing to patch curl-rust.

In my case I need to set `CURLOPT_FTP_USE_EPSV` to `0` to connect to a particular FTP server as it hangs on the `EPSV` command.

**Comment by ebarnard** [comment]
I just discovered `Easy::raw()` when trying to implement this. Perhaps it should be mentioned in the docs for `Easy` and `Easy2`.

**Comment by alexcrichton** [comment]
Thanks for the report! And yeah I'd prefer to avoid doing this and instead enabled it with the with the `raw` accessor instead. Documenting that seems fine too :)

Also FWIW the vision I had was that all options would have their own dedicated methods, which we could document, type, etc. I think it'd be fine to add this as a method as well.

**Comment by ebarnard** [comment]
> Also FWIW the vision I had was that all options would have their own dedicated methods, which we could document, type, etc. I think it'd be fine to add this as a method as well.

I was going to do that for the options I've used but it's going to be a random assortment of FTP options. I'm not sure I have the inclination to add all of them.

**Comment by albel727** [comment]
I would have much preferred if `getopt_long()` and friends were exposed. "Method per option" doesn't even work for me, because I want to not only set but also get some options back and it doesn't look like the current methodology even intends providing both a getter and a setter for any given option, at least I see no consistent naming scheme e.g. `get_xxx()/set_xxx()` that would indicate otherwise. I can of course make do with `raw()`, but it's a total shame that I then have to reimplement the conversion and error handling logic, when it's actually already there.

**Comment by ZelCloud** [comment]
Can this be reconsidered,  `curl_easy_setopt` and `curl_easy_getinfo` provide a lot of useful additions, and while its possible to get by with `raw` having to reduplicate all the existing curl logic that already exists seems terrible.
