### ISSUE TITLE
Retrieve server certificate

### ISSUE THREAD

**Issue by MikeCamel** [alexcrichton/curl-rust#370]
Is there a simple way to retrieve the certificate presented by the server for manual checking?

` curl --insecure -vvI` gives you pretty much everything, and I'm looking for something similar (or certificate-specific) to allow parsing of self-signed certificates, for instance.

Note - I've tried `certinfo(true)`, but can't find any way to output the information, and `ssl_verify_host(false)` doesn't seem to help.

Thanks.

**Comment by sagebind** [comment]
The counterpart to [`CURLOPT_CERTINFO`](https://curl.se/libcurl/c/CURLOPT_CERTINFO.html) is to call [`curl_easy_getinfo(easy, CURLINFO_CERTINFO, ptr)`](https://curl.se/libcurl/c/CURLINFO_CERTINFO.html) in order to get the information that the first method call enables. Currently we don't provide safe Rust bindings to this API, though this is something we could add.

> Is there a simple way to retrieve the certificate presented by the server for manual checking?

Note that `CURLOPT_CERTINFO` does not necessarily give you access to the actual certificate, but rather metadata about the certificate that the TLS engine chooses to return. Some TLS engines don't return anything. I would not use this API to do manual certificate validation, especially because by the time you get access to this info, curl has already connected to the server and started performing the transfer.

In the C API, the way to customize cert validation is to use [`CURLOPT_SSL_CTX_FUNCTION`](https://curl.se/libcurl/c/CURLOPT_SSL_CTX_FUNCTION.html), which should comes with the significant caveats that (1) it only works for certain TLS engines, (2) requires you to know specific details about the TLS engine's API, and (3) is very unsafe and easy to cause security vulnerabilities. For these reasons it isn't really something we'd want to expose at all in safe Rust bindings.

**Comment by sagebind** [comment]
Closing for now, since adding bindings to `CURLINFO_CERTINFO` wouldn't help in the scenario raised, and I do not think it is possible to create a safe API around `CURLOPT_SSL_CTX_FUNCTION`. If you really need to use `CURLOPT_SSL_CTX_FUNCTION` then you can use the unsafe API by using [`Easy::raw`](https://docs.rs/curl/0.4.34/curl/easy/struct.Easy.html#method.raw) and the `curl-sys` crate.

**Comment by bramp** [comment]
Happy to open a new issue, but I was also looking for CURLINFO_CERTINFO bindings today. Not to validate the certificate, but to record information it contained (at the time of the request).
