### ISSUE TITLE
Wish:   Document `cargo publish` of this crate

### ISSUE THREAD

**Issue by stappersg** [alexcrichton/curl-rust#450]
Hello,

At https://crates.io/crates/curl-sys are releases with version numbers like `0.4.55+curl-7.83.1`.

At https://github.com/alexcrichton/curl-rust/tags is no sign of the `+curl-7.83.1`.   I wonder where it does come from.

Please document the process of `cargo publish` for this crate.
Tell about the magic of adding _plus curl version number_.

**Comment by sagebind** [comment]
The full version number as published on Crates.io is set [in the `Cargo.toml` file for the crate](https://github.com/alexcrichton/curl-rust/blob/df9d05cf15409a67aeafa16a2b602973c7d0c7f2/curl-sys/Cargo.toml#L3). The string after the `+` character is defined as _build metadata_ by the [Semantic Versioning spec](https://semver.org/#spec-item-10). It is ignored when comparing version numbers, but is useful for indicating other useful build info in the version number. In the case of the `curl-sys` crate, we use the build metadata to indicate which upstream version of libcurl is bundled with the crate version at a glance.

We do not include the build metadata in the Git tags because there's not really as much value to it, and it makes checking out the Git tags a bit more tedious.

**Comment by stappersg** [comment]
> The full version number as published on Crates.io is set [in the Cargo.toml file for the crate](https://github.com/alexcrichton/curl-rust/blob/df9d05cf15409a67aeafa16a2b602973c7d0c7f2/curl-sys/Cargo.toml#L3).
```text
version = "0.4.55+curl-7.83.1"
```

Ah thanks, that answers my
> At https://github.com/alexcrichton/curl-rust/tags is no sign of the +curl-7.83.1. I wonder where it does come from.

So there is **no  magic** of adding _plus curl version number_.

Thanks again.
(original poster (closing the issue))
