### ISSUE TITLE
rustls does not work on windows

### ISSUE THREAD

**Issue by tyhdefu** [alexcrichton/curl-rust#455]
Trying a post request on windows with the rustls feature enabled leads to:
`Error { description: "SSL peer certificate or SSH remote key was not OK", code: 60, extra: Some("invalid peer certificate signature") }`
I have set up a minimal reproduceable example on github, and added github actions to prove that it works on linux but not on windows.
https://github.com/tyhdefu/curl-rs-test
[Windows Failing](https://github.com/tyhdefu/curl-rs-test/runs/7845639388?check_suite_focus=true)
[Ubuntu Succeeding](https://github.com/tyhdefu/curl-rs-test/runs/7845639390?check_suite_focus=true)
Interestingly, it also does not seem to work when run on WSL, (although a full arch vm worked) and when cross compiled to a raspberry pi (armv6l) it also produces the same error.
Let me know if you need any more information.

**Comment by sagebind** [comment]
This is because rustls does not come with any trusted root certificates, nor any ability to automatically discover certificates trusted by the operating system. This differs from other TLS backends which typically have some way to auto-discover trusted certificates.

To use rustls with curl, you must specify at least one certificate to trust using [`cainfo`](https://docs.rs/curl/latest/curl/easy/struct.Easy2.html#method.cainfo) or [`ssl_cainfo_blob`](https://docs.rs/curl/latest/curl/easy/struct.Easy2.html#method.ssl_cainfo_blob). At least at this time, the curl crate does not to anything extra beyond what libcurl provides to auto-discover certificates.

**Comment by sagebind** [comment]
Closing as this is primarily an unfriendliness/inconvenience on rustls/curl's part, and not the fault of this crate. If you disagree feel free to reopen!
